stages:
  - sync

sync:
  stage: sync
  script:
    - git remote add github https://github.com/CAREamics/careamics-reproducibility.git
    - git fetch github
    - git checkout main
    - git pull github main
    - git push origin main
  only:
    - schedules

