# ============================================================
# Sync GitHub Public Repo -> Private GitLab Repo
# This pipeline pulls from GitHub and pushes to GitLab private
# repository in order to maintain synchronization between the
# two repositories.
# ============================================================
stages:
  - sync

variables:
  USER: $CI_DEPLOY_USER
  TOKEN: $GITLAB_TOKEN

sync:
  stage: sync
  image:
    name: hugomods/hugo
    entrypoint: [""]
  script:
    # Install necessary tools
    - apk add --no-cache git openssh

    # Checkout main
    - git checkout main

    # Add Github remote
    - git remote add github https://github.com/CAREamics/careamics-reproducibility.git

    # Add Gitlab remote
    - git remote add gitlab "https://${USER}:${TOKEN}@gitlab.fht.org/CAREamics/careamics-reproducibility.git"

    # Pull from Github
    - git pull github main

    # Push to GitLab
    - git push gitlab main
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - when: never # Ensures job doesn't run on push/merge/PR
