stages:
  - sync

variables:
  TOKEN: GITLAB_TOKEN

sync:
  stage: sync
  image:
    name: hugomods/hugo
    entrypoint: [""]
  script:
    # Install necessary tools
    - apk add --no-cache git openssh

    # Checkout main
    - git checkout main

    # Add Github remote
    - git remote add github https://github.com/CAREamics/careamics-reproducibility.git

    # Add Gitlab remote
    - git remote add gitlab "https://gitlab-ci-token:${TOKEN}@gitlab.fht.org/CAREamics/careamics-reproducibility.git"

    # Pull from Github
    - git pull github main

    # Push to GitLab
    - git push gitlab main
