stages:
  - sync

# variables:
# BUILD: MYCUSTOMBUILD
# GIT_STRATEGY: none # prevent GitLab from doing an initial git clone

sync:
  stage: sync
  image:
    name: hugomods/hugo
    entrypoint: [""]
  script:
    # Install necessary tools
    - apk add --no-cache git openssh

    # Checkout main
    - git checkout main

    # Add Github remote
    - git remote add github https://github.com/CAREamics/careamics-reproducibility.git

    # Pull from Github
    - git pull github main

    # Push to GitLab
    - git push origin main
    # - git push "https://gitlab-ci-token:${GITLAB_TOKEN}@gitlab.fht.org/CAREamics/careamics-reproducibility.git"
