stages:
  - sync

# variables:
# BUILD: MYCUSTOMBUILD
# GIT_STRATEGY: none # prevent GitLab from doing an initial git clone

sync:
  stage: sync
  image:
    name: hugomods/hugo
    entrypoint: [""]
  script:
    # Install necessary tools
    - apk add --no-cache git openssh
    - git remote show origin

    # Clone public GitHub repo (read-only)
    # - git clone --mirror https://github.com/your-org/your-repo.git github-upstream

    # # Setup Git identity
    # - git config --global user.name "CI Sync Bot"
    # - git config --global user.email "ci-sync@example.com"

    # # Push to GitLab using personal access token or CI job token
    # - cd github-upstream
    # - git remote set-url --push origin "https://oauth2:${GITLAB_TOKEN}@gitlab.com/your-group/your-private-repo.git"
    # - git push --mirror
